development:
  adapter: postgresql
  encoding: unicode
  database: onboard_development
  pool: 5
  username: jtg
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: onboard_test
  pool: 5
  username: jtg
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: onboard_production
  pool: 5
  username: onboard
  password:
